version: "3.8"

services:
  devcontainer:
    image: ghcr.io/astral-sh/uv:python3.11-bookworm
    command: sleep infinity
    volumes:
      - .:/workspaces/enterprise-aura
    working_dir: /workspaces/enterprise-aura
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/aura_test?authSource=admin
      MONGO_DB: aura_test
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: aura-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: aura_test
    volumes:
      - ./tmp/mongo:/data/db
      - ./aura_v2/infrastructure/persistence/migrations:/docker-entrypoint-initdb.d:ro
