services:
  mongo:
    image: mongo:7.0
    container_name: aura-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME:-root}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD:-example}"
      MONGO_INITDB_DATABASE: "${MONGO_DB:-aura_test}"
    volumes:
      - ./tmp/mongo:/data/db
      - ./aura_v2/infrastructure/persistence/migrations:/docker-entrypoint-initdb.d:ro
