# pyproject.toml
[project]
name = "aura-v2"
version = "2.0.0"
requires-python = ">=3.10"

[project.dependencies]
# Core Domain
pydantic = "^2.5"
numpy = "^1.24"
attrs = "^23.1"

# SOTA Tracking Algorithms
boxmot = "^10.0.0"
ultralytics = "^8.0.0"
supervision = "^0.16.0"
deep-sort-realtime = "^1.3"

# Sensor Fusion & Filtering
filterpy = "^1.4.5"
scipy = "^1.11"
scikit-learn = "^1.3"

# Infrastructure
dependency-injector = "^4.41"
asyncio = "^3.4.3"
aioredis = "^2.0"
motor = "^3.3"  # Async MongoDB
aiokafka = "^0.10"  # Event streaming

# Evaluation
trackeval = "^1.0.0"
lap = "^0.4.0"  # Linear assignment

# Observability
opentelemetry-api = "^1.20"
opentelemetry-sdk = "^1.20"
prometheus-client = "^0.18"
structlog = "^23.2"

# Performance
numba = "^0.58"  # JIT compilation
cupy = "^13.0"  # GPU arrays
tensorrt = "^8.6"

# API
fastapi = "^0.104"
grpcio = "^1.59"
websockets = "^12.0"