line-length = 100

[lint]
select = ["E","F","B","I"]
ignore = ["I001","I002"]  # no I003

[format]
quote-style = "preserve"

[lint.per-file-ignores]
"aura_v2/diagnostic_dashboard.py" = ["E501"]
"aura_v2/setup_dashboard.py"      = ["E501","F401"]
"aura_v2/main.py"                 = ["E501"]
"aura_v2/domain/pipeline/fusion_pipeline.py" = ["E501"]
"aura_v2/domain/__init__.py"      = ["F403"]
"aura_v2/infrastructure/adapters/legacy/bridge.py" = ["E402","F841"]
"scripts/check_init_imports.py"   = ["E501"]
"tests/fusion/test_end_to_end_fuse.py" = ["E501"]
