line-length = 100

[lint]
select = ["E","F","B","I"]
ignore = []

[format]
quote-style = "preserve"

[lint.per-file-ignores]
"aura_v2/diagnostic_dashboard.py"            = ["E501"]
"aura_v2/setup_dashboard.py"                 = ["E501","F401"]
"aura_v2/main.py"                            = ["E501"]
"aura_v2/domain/pipeline/fusion_pipeline.py" = ["E501"]
"aura_v2/test_dashboard_setup.py"            = ["F401"]
