name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -fsSL https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Create venv with uv
        run: |
         uv venv .venv
         echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
         echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Setup Development Dashboard  
        run: python -m aura_v2.setup_dashboard

      - name: Test Dashboard
        run: python -c "from aura_v2.web_dashboard.api import router; print('Dashboard ready')"

      - name: Install project (editable) + extras
        run: |
          uv pip install -e .
          uv pip install -e ".[tracking,observability,messaging,perf,test]"

      - name: Run tests
        run: |
          uv pip install -q pytest pytest-asyncio httpx anyio
          uv run pytest
